-- One row per (item/service + payer plan), columns align to CMS Tall (subset)
CREATE TABLE IF NOT EXISTS hpt.standard_charge (
  id BIGSERIAL PRIMARY KEY,
  hospital_name TEXT,
  hospital_location TEXT,
  last_updated_on DATE,
  version TEXT,
  financial_aid_policy TEXT,
  license_number TEXT,
  setting TEXT,
  billing_class TEXT,
  description TEXT,
  code_1 TEXT, code_1_type TEXT,
  code_2 TEXT, code_2_type TEXT,
  code_3 TEXT, code_3_type TEXT,
  drug_unit_of_measurement TEXT,
  drug_type_of_measurement TEXT,
  modifiers TEXT,
  standard_charge_gross NUMERIC,
  standard_charge_discounted_cash NUMERIC,
  payer_name TEXT,
  plan_name TEXT,
  standard_charge NUMERIC,
  standard_charge_percent NUMERIC,
  standard_charge_min NUMERIC,
  standard_charge_max NUMERIC,
  contracting_method TEXT,
  additional_generic_notes TEXT,
  source_file TEXT,
  ingested_at TIMESTAMPTZ DEFAULT now()
);
